### ISSUE TITLE
Listed Unsolved Contribution on your Contributions Section

### ISSUE THREAD

**Issue by seoeunHong** [ossd-s23/jiawei-zhang-a-weekly#1]
In the Contributions section, you list unsolved issues as contributions. I think it would be better to include the links to these issues after they are solved.

Additionally, it's recommended to use the Markdown link syntax, such as `[Contribution Link](http://...)`, instead of just displaying the URL of the link.

**Comment by jiawei-zhang-a** [comment]
I am so sorry for replying late, I did not get notified by github of your issue. I will remove this one and edit the markdown style

**Comment by seoeunHong** [comment]
Oh it's okay :) and thank for taking my recommendation! Hopefully it makes your blog prettier
